export interface GameText {
  id: number;
  char: string;
  description?: string;
}

export const gameTexts: GameText[] = [
  { id: 1, char: "爱", description: "表示对人或事物的深厚感情" },
  { id: 2, char: "和", description: "表示和谐、和睦" },
  { id: 3, char: "美", description: "表示美丽、美好" },
  { id: 4, char: "善", description: "表示善良、善行" },
  { id: 5, char: "真", description: "表示真实、真诚" },
  { id: 6, char: "智", description: "表示智慧、聪明" },
  { id: 7, char: "勇", description: "表示勇敢、勇气" },
  { id: 8, char: "信", description: "表示诚信、信任" },
  { id: 9, char: "礼", description: "表示礼貌、礼仪" },
  { id: 10, char: "义", description: "表示正义、道义" },
  { id: 11, char: "孝", description: "表示孝顺、孝敬" },
  { id: 12, char: "忠", description: "表示忠诚、忠心" },
  { id: 13, char: "仁", description: "表示仁爱、仁慈" },
  { id: 14, char: "德", description: "表示道德、品德" },
  { id: 15, char: "诚", description: "表示诚实、诚信" },
  { id: 16, char: "敬", description: "表示尊敬、敬重" },
  { id: 17, char: "谦", description: "表示谦虚、谦逊" },
  { id: 18, char: "让", description: "表示谦让、礼让" },
  { id: 19, char: "勤", description: "表示勤奋、勤劳" },
  { id: 20, char: "俭", description: "表示节俭、俭朴" },
  { id: 21, char: "乐", description: "表示快乐、欢乐" },
  { id: 22, char: "福", description: "表示幸福、福气" },
  { id: 23, char: "寿", description: "表示长寿、寿命" },
  { id: 24, char: "康", description: "表示健康、安康" },
  { id: 25, char: "宁", description: "表示安宁、宁静" },
];

export const phraseList = [
  { id: 1, phrase: "东边", pinyin: "dōng biān", vietnamese: "phía đông" },
  { id: 2, phrase: "书店", pinyin: "shū diàn", vietnamese: "hiệu sách" },
  { id: 3, phrase: "儿子", pinyin: "ér zi", vietnamese: "con trai" },
  { id: 4, phrase: "儿歌", pinyin: "ér gē", vietnamese: "bài hát thiếu nhi" },
  { id: 5, phrase: "出去", pinyin: "chū qù", vietnamese: "ra ngoài" },
  { id: 6, phrase: "包子", pinyin: "bāo zi", vietnamese: "bánh bao" },
  { id: 7, phrase: "吃饭", pinyin: "chī fàn", vietnamese: "ăn cơm" },
  { id: 8, phrase: "唱歌", pinyin: "chàng gē", vietnamese: "hát" },
  { id: 9, phrase: "多少", pinyin: "duō shǎo", vietnamese: "bao nhiêu" },
  { id: 10, phrase: "大学", pinyin: "dà xué", vietnamese: "đại học" },
  { id: 11, phrase: "好吃", pinyin: "hǎo chī", vietnamese: "ngon" },
  { id: 12, phrase: "工作", pinyin: "gōng zuò", vietnamese: "công việc / làm việc" },
  { id: 13, phrase: "帮忙", pinyin: "bāng máng", vietnamese: "giúp đỡ" },
  { id: 14, phrase: "开车", pinyin: "kāi chē", vietnamese: "lái xe" },
  { id: 15, phrase: "打包", pinyin: "dǎ bāo", vietnamese: "gói mang về" },
  { id: 16, phrase: "打开", pinyin: "dǎ kāi", vietnamese: "mở ra" },
  { id: 17, phrase: "打车", pinyin: "dǎ chē", vietnamese: "gọi xe / bắt taxi" },
  { id: 18, phrase: "放学", pinyin: "fàng xué", vietnamese: "tan học" },
  { id: 19, phrase: "爱好", pinyin: "ài hào", vietnamese: "sở thích" },
  { id: 20, phrase: "白天", pinyin: "bái tiān", vietnamese: "ban ngày" },
  { id: 21, phrase: "白饭", pinyin: "bái fàn", vietnamese: "cơm trắng" },
  { id: 22, phrase: "读书", pinyin: "dú shū", vietnamese: "đọc sách" },
  { id: 23, phrase: "非常", pinyin: "fēi cháng", vietnamese: "rất" },
  { id: 24, phrase: "飞机", pinyin: "fēi jī", vietnamese: "máy bay" },
  { id: 25, phrase: "饭店", pinyin: "fàn diàn", vietnamese: "nhà hàng / khách sạn" },
  { id: 26, phrase: "高兴", pinyin: "gāo xìng", vietnamese: "vui vẻ" },
];
